#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

begin
  require "dotfiled"
rescue LoadError
  puts "Could not load dotfiles"
end

puts Dotfiled::AlternativeFile::Finder.new.execute(ARGV.dup)
